spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-toucheese-3.cja2kuiisy1n.ap-northeast-2.rds.amazonaws.com/TOUCHEESE?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: gamsungping3

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 1000
    open-in-view: false

  jackson:
    time-zone: Asia/Seoul