INSERT INTO region (name) VALUES ('강남/서초/송파');
INSERT INTO region (name) VALUES ('강서/마포/영등포');
INSERT INTO region (name) VALUES ('강북/용산/성동');
INSERT INTO studio (name, profile_price, region_id) VALUES ('Studio 1', 120000, 1);
INSERT INTO studio (name, profile_price, region_id) VALUES ('Studio 2', 140000, 1);
INSERT INTO studio (name, profile_price, region_id) VALUES ('Studio 3', 90000, 2);
INSERT INTO studio (name, profile_price, region_id) VALUES ('Studio 4', 100000, 2);
INSERT INTO studio (name, profile_price, region_id) VALUES ('Studio 5', 100000, 3);
INSERT INTO studio (name, profile_price, region_id) VALUES ('Studio 6', 110000, 3);
INSERT INTO studio (name, profile_price, region_id) VALUES ('Studio 7', 230000, 3);
INSERT INTO studio (name, profile_price, region_id) VALUES ('Studio 8', 80000, 3);
INSERT INTO studio (name, profile_price, region_id) VALUES ('Studio 9', 50000, 1);
INSERT INTO studio (name, profile_price, region_id) VALUES ('Studio 10', 400000, 2);
INSERT INTO studio (name, profile_price, region_id) VALUES ('Studio 11', 100000, 3);
INSERT INTO concept (name) VALUES ('생동감있는');
INSERT INTO concept (name) VALUES ('플래쉬+유광');
INSERT INTO concept (name) VALUES ('선명한');
INSERT INTO concept (name) VALUES ('수채화 그림체');
INSERT INTO member (name) VALUES ('member1');
INSERT INTO member (name) VALUES ('member2');
INSERT INTO member (name) VALUES ('member3');
INSERT INTO member (name) VALUES ('member4');
INSERT INTO member (name) VALUES ('member5');
INSERT INTO studio_concept (concept_id, studio_id) VALUES (1, 1);
INSERT INTO studio_concept (concept_id, studio_id) VALUES (1, 2);
INSERT INTO studio_concept (concept_id, studio_id) VALUES (2, 3);
INSERT INTO studio_concept (concept_id, studio_id) VALUES (2, 4);
INSERT INTO studio_concept (concept_id, studio_id) VALUES (3, 5);
INSERT INTO studio_concept (concept_id, studio_id) VALUES (3, 6);
INSERT INTO studio_concept (concept_id, studio_id) VALUES (4, 7);
INSERT INTO studio_concept (concept_id, studio_id) VALUES (4, 8);
INSERT INTO studio_concept (concept_id, studio_id) VALUES (4, 9);
INSERT INTO studio_concept (concept_id, studio_id) VALUES (3, 10);
INSERT INTO studio_concept (concept_id, studio_id) VALUES (2, 11);
INSERT INTO rating (studio_id, member_id, rating, created_at) VALUES (2, 1, 5, NOW());
INSERT INTO rating (studio_id, member_id, rating, created_at) VALUES (2, 2, 4, NOW());
INSERT INTO rating (studio_id, member_id, rating, created_at) VALUES (2, 3, 4, NOW());
INSERT INTO rating (studio_id, member_id, rating, created_at) VALUES (1, 4, 3, NOW());
INSERT INTO rating (studio_id, member_id, rating, created_at) VALUES (1, 5, 3, NOW());