INSERT INTO Toucheese.region (name) VALUES ('강남/서초/송파');
INSERT INTO Toucheese.region (name) VALUES ('강서/마포/영등포');
INSERT INTO Toucheese.region (name) VALUES ('강북/용산/성동');
INSERT INTO Toucheese.studio (name, region_id) VALUES ('Studio 1',1);
INSERT INTO Toucheese.studio (name, region_id) VALUES ('Studio 2',1);
INSERT INTO Toucheese.studio (name, region_id) VALUES ('Studio 3',2);
INSERT INTO Toucheese.studio (name, region_id) VALUES ('Studio 4',2);
INSERT INTO Toucheese.studio (name, region_id) VALUES ('Studio 5',3);
INSERT INTO Toucheese.studio (name, region_id) VALUES ('Studio 6',3);
INSERT INTO Toucheese.concept (name) VALUES ('생동감있는');
INSERT INTO Toucheese.concept (name) VALUES ('플래쉬+유광');
INSERT INTO Toucheese.concept (name) VALUES ('선명한');
INSERT INTO Toucheese.concept (name) VALUES ('수채화 그림체');
INSERT INTO Toucheese.member (name) VALUES ('member1');
INSERT INTO Toucheese.member (name) VALUES ('member2');
INSERT INTO Toucheese.member (name) VALUES ('member3');
INSERT INTO Toucheese.member (name) VALUES ('member4');
INSERT INTO Toucheese.member (name) VALUES ('member5');
insert into Toucheese.studio_concept (concept_id, studio_id) value (1, 1);
insert into Toucheese.studio_concept (concept_id, studio_id) value (1, 2);
insert into Toucheese.studio_concept (concept_id, studio_id) value (2, 3);
insert into Toucheese.studio_concept (concept_id, studio_id) value (2, 4);
insert into Toucheese.studio_concept (concept_id, studio_id) value (3, 5);
insert into Toucheese.studio_concept (concept_id, studio_id) value (3, 6);
INSERT INTO Toucheese.rating (studio_id, member_id, rating, created_at) VALUES (2, 1, 5, NOW());
INSERT INTO Toucheese.rating (studio_id, member_id, rating, created_at) VALUES (2, 2, 4, NOW());
INSERT INTO Toucheese.rating (studio_id, member_id, rating, created_at) VALUES (2, 3, 4, NOW());
INSERT INTO Toucheese.rating (studio_id, member_id, rating, created_at) VALUES (1, 4, 3, NOW());
INSERT INTO Toucheese.rating (studio_id, member_id, rating, created_at) VALUES (1, 5, 3, NOW());
